# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

  platform :android do
      desc "Submit a new version Build to QA"
      lane :qa do
          increment_version_code(
             gradle_file_path: "buildSrc/src/main/java/Dependencies.kt",
             ext_constant_name: "versionCode"
             #app_folder_name:"app"
          )
          gradle(
            task: 'assemble',
            flavor: "qa",
            build_type: 'Release'
          )

          firebase_app_distribution(
              app: "ID DE FIREBASE",
              groups: "GRUPO DE FIREBASE",
              release_notes: "Version Apuntando a QA!"
          )

      end

  desc "Submit a new version Build to DEV"
      lane :dev do
         increment_version_code(
                   gradle_file_path: "buildSrc/src/main/java/Dependencies.kt",
                   ext_constant_name: "versionCode"
                   #app_folder_name:"app"
           )
           gradle(
             task: 'assemble',
             flavor: "dev",
             build_type: 'Release'
          )
          firebase_app_distribution(
              app: "ID DE FIREBASE",
              groups: "GRUPO DE FIREBASE",
              release_notes: "Version Apuntando a DEV!"
          )

  end

  desc "Submit a new version Build to PROD"
        lane :prod do
           increment_version_code(
                gradle_file_path: "buildSrc/src/main/java/Dependencies.kt",
                ext_constant_name: "versionCode"
                #app_folder_name:"app"
             )
           gradle(
             task: 'assemble',
             flavor: "prod",
             build_type: 'Release'
           )
            firebase_app_distribution(
                app: "ID DE FIREBASE",
                groups: "GRUPO DE FIREBASE",
                release_notes: "Version Apuntando a PROD!"
            )
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

    after_all do |lane|
      # This block is only called if executed lane was successful
      slack(
         message: "MENSAJE PARA SLACK EN EL DEPLOY",
         icon_url: "URL DE ICONO PARA SLACK"
      )
    end

    error do |lane, exception|
      slack(
         message: exception.message,
         success: false
      )
    end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

